### ISSUE TITLE
Cannot see autosuggestion in add new address popup on checkout page

### ISSUE THREAD

**Issue by parth-synoptek** [shipperhq/module-address-autocomplete#17]
![image](https://user-images.githubusercontent.com/47375146/61129241-98c9e880-a4d1-11e9-93c2-b0da9b98ebd3.png)

**Comment by sd1cko81** [comment]
Any update on this issue? I can confirm this is the case for me too.

**Comment by ibraheemnabeelfauzi** [comment]
Hi @parth-synoptek & @sd1cko81  
Thanks for bringing this to our attention. We'll look into it and provide you with more details soon.

**Comment by ibraheemnabeelfauzi** [comment]
Hi @parth-synoptek & @sd1cko81 - Just wanted to follow up and let you know folks that this functionality is currently not supported when you're logged in and try to add another address on the **checkout**, it's only supported when you try to enter an address on the checkout itself & from within the address book itself - therefore this makes it a feature request which I've gone ahead and raise this to my lead engineers - we'll update you once we establish whether we'll notify you with our course of action once we determine if we're going to add it or not.

**Comment by wsadasmit** [comment]
Hi @parth-synoptek & @sd1cko81 - After investigating this issue we've determined that this functionality should currently be operational. Attached is a screenshot which reflects this.

If this is not working on your environment, it is possible this is caused by an issue with your Google API key. If you check the javascript console, you may find errors similar to the second image I've attached here.
![address_autocomplete_01](https://user-images.githubusercontent.com/40184433/69742765-eb174900-1102-11ea-89ca-3aaaa6f0894a.png)
![address_autocomplete_02](https://user-images.githubusercontent.com/40184433/69742764-eb174900-1102-11ea-936e-ff9e23d556d2.png)

**Comment by realadityayadav** [comment]
@wsadasmit @wsagen This doesnt work for me on 2.3.5-p2 Magento version. Any heads up to this?
